config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, only: [:index] do
    get :search, :on => :collection
  end

  resources :shops, only: [:index, :show]  do
    get 'add/:id',    to: 'ordered_products#add',     as: 'add'
    get 'remove/:id', to: 'ordered_products#remove',  as: 'remove'
    get 'reduce/:id', to: 'ordered_products#reduce',  as: 'reduce'
  end


  namespace :retailer do
    resources :shops, only: [:index, :show] do
      resources :orders, only: [:show, :update]
    end
  end

  resources :orders, only: [:index, :create, :update, :show]

  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'translations/dictionnary', to: 'translations#dictionnary'
      post 'translations/translate', to: 'translations#translate'
      get 'shops/search', to: 'shops#search'

      resources :translations, only: [ :new ]
    end
  end
  # get '/style', to: 'pages#bootstrap_components'
  get '/clear-session', to: 'orders#clear_session_cart'
end

app/models/shop.rb
class Shop < ApplicationRecord
  include PgSearch

  belongs_to :user
  belongs_to :category

  has_many :opening_hours, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :product_categories, through: :products
  has_attachment :photo

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :name, uniqueness: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  after_create :set_owner

  pg_search_scope :search_products_shops,
    associated_against: {
      products: [ :name, :short_description, :description ]
    }

  def to_hash
    categories = self.product_categories.distinct
    hash = {}
    categories.each do |category|
      products = self.products.where(product_category: category)
      hash[category.name] = products
    end
    hash
  end

  def self.search_by_address(params)
    if params[:category].nil? || params[:category].empty?
      params[:where].blank? ? shops = Shop.all.page(params[:page]) : shops = Shop.near(params['where'], 1000).page(params[:page])
    else
      params[:where].blank? ? shops = Shop.where(category_id: params[:category]).page(params[:page]) : shops = Shop.near(params['where'], 1000).where(category_id: params[:category]).page(params[:page])
    end
    shops
  end

  def self.search_by_latlng(params)
    dist = params[:dist] || 5
    latlng = [params[:lat], params[:lng]] || [44.84044, -0.5805]
    category_id = Category.find_by name: params[:category].capitalize
    shops = Shop.near(latlng, dist).where(category_id: category_id)
  end

  private

  def set_owner
    self.user.owner! unless self.user.owner?
  end
end

app/controllers/api/v1/shops_controller.rb
class Api::V1::ShopsController < Api::V1::BaseController
  def search
    @shops = Shop.search_by_latlng(params)
    # render json: @shops
  end
end

app/controllers/retailer/shops_controller.rb
class Retailer::ShopsController < ApplicationController
  def index

    if current_user.shops.one?
      redirect_to retailer_shop_path(current_user.shops.first)
      return
    end
    # Let's anticipate on next week (with login)
    @shops = current_user.shops
    # @shop = current_user.shops.find(params[:id])
  end

  def show
    @shop = Shop.find(params[:id])
    @orders = @shop.orders
    # @orders_in  = @orders.where("pick_up_at > ?", Date.today )
    # @orders_out = @orders.where("pick_up_at < ?", Date.today )
    @orders_confirmed  = @orders.where(status: :confirmed)
    @orders_ready = @orders.where(status: :ready)
    @orders_history = @orders.where(status: :picked_up)

  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :find_shop, only: [:show]

  def index
    respond_to do |format|
      format.html {
        @shops = Shop.search_by_address(params)
        session[:address] = params['where']
        @hash = build_markers(@shops)
      }
      format.json {
        @shops = Shop.search_by_latlng(params)
      }
    end
  end

  def show
    @shops = Shop.near(@shop,5).limit(4).offset(1)
    @today = Date.today
    @open_hours = OpeningHour.where(shop_id: params[:id])
    @collection = OpenHourSort.new(@open_hours).call  ## unless @open_hours.empty?
    @cart = session[:cart] || {} #set to empty hash if empty (new cart)
    @product_hash = @shop.to_hash
  end

  private

  def build_markers(shops)
    markers = Gmaps4rails.build_markers(shops) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow render_to_string(partial: "/shared/map_box", locals: { shop: shop })
    end
    markers
  end

  def find_shop
    @shop = Shop.find(params[:id])
  end

  def find_relative_distances(centre)
    location = Geocoder.coordinates(centre)
    if location
      @shops.each do |shop|
        shop.distance = Geocoder::Calculations.distance_between(location, [shop.latitude, shop.longitude]).truncate
      end
    end
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
  def distance(dist)
    return '' unless dist
    if dist > 1
      return "#{dist.round(1)} km"
    else
      return "#{(dist.round(2) * 1000).truncate} m"
    end
  end

  def number_of_items(carts)
    return 0 if carts.blank?
    sum = 0
    carts.each do |shop_id, cart|
      sum += number_of_subitems(cart)
    end
    sum
  end

  def number_of_subitems(cart)
    return 0 if cart.blank?
    sum = 0
    cart.each do |_, product|
      sum += product['qty']
    end
    sum
  end

  def cart_total(carts)
    return 0 if carts.blank?
    sum = 0
    carts.each do |shop_id, cart|
      sum += cart_sub_total(cart)
    end
    sum.round(2)
  end

  def cart_sub_total(cart)
    return 0 if cart.blank?
    sum = 0
    cart.each do |product_id, product|
      sum += product['qty'] * product['price']
    end
    sum
  end
end

app/views/shops/_badge.html.erb
<%= number_of_items session[:cart] %>

app/views/shops/_card.html.erb
<%= link_to shop_path(shop) do %>
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path shop.photo.path, width: 225, quality: "auto:eco", crop: :fill unless shop.photo.nil? %>');">
      <div class="card-category">
          <h4><%= shop.name.capitalize %></h4>
      </div>
      <%#= render 'shared/stars', rating: shop.avg_rating.nil? ? 0 : shop.avg_rating %>
      <% if shop.try(:distance) %>
        <div class="card-distance">
          <%= distance shop.try(:distance) %>
        </div>
      <% end %>
      <div class="card-description">
        <%= shop.category.name.upcase %>
      </div>
<!--       <div class="card-description">
        <p class="address-shop"><%= shop.address %></p>
      </div> -->
  </div>

<% end %>

app/views/shops/_cart.html.erb
<% if @cart %>
  <% @cart.each do |shop_id, orders| %>
  <div class="cart-lines">
    <% if Shop.exists?(id: shop_id) %>
      <h4><%= Shop.find(shop_id).name.capitalize %></h4>
      <% orders.each do |product_id, product| %>
        <%= render 'shops/cart_line', id: product_id, product: product, shop_id: shop_id %>
      <% end %>
    <% end %>
  </div>
  <% end %>
  <div class="cart-line ">
    <h4 class="cart-line-content text-bold">
      Total
    </h4>
    <h4 class="cart-line-price text-bold">
      <%= cart_total @cart %> €
    </h4>
  </div>

<% end %>

app/views/shops/_cart_line.html.erb
<div class="cart-line" id="<%= "product-#{id}" %>">
  <div class="cart-line-content">
    <span class="cart-line-quantity">
      <%= product['qty']  %> x
    </span>
    <span class="cart-product-name">
      <%= product['name'] %>
    </span>
  </div>
  <div class="cart-line-price">
    <%= product['price'] %> €
  </div>
  <%=  link_to shop_remove_path(shop_id, id), class: 'cart-line-controls', remote: true do %>
    <i class="fa fa-times" aria-hidden="true"></i>
  <% end %>
</div>

app/views/shops/_form_order.html.erb
<div class="shop-order">
  <%= simple_form_for Order.new() do |f| %>

    <%= simple_fields_for :other do |o| %>
      <div class="row">
        <div class="col-sm-7">
          <%= o.input :day, collection: [
            @today.strftime("%d-%b-%y"),
            @today.next.strftime("%d-%b-%y"),
            @today.next_day(2).strftime("%d-%b-%y")],
            label: false, selected: 0 %>
        </div>

        <div class="col-sm-5">
          <!--["12h - 12h30", "15h - 15h30", "16h - 16h30"] -->
          <%= o.input :hour, collection: @collection, label: false, selected: 0 %>
        </div>
      </div>
    <% end %>
    <%= f.input :instructions, input_html: { id: 'instructions' }, :as => "hidden" %>

  <div class="comment-order">
    <span id="instruction-text"></span>
    <span class="comment-link">
    <%= link_to "Ajouter un commentaire à ma commande", '#', :id => 'comment', "data-toggle" => "modal", 'data-target' => '#CommentOrder' %>
    </span>
  </div>

    <div class="form-actions">
      <%= f.button :submit, 'Commander', class: "btn btn-success btn-lg btn-block" %>
    </div>
  <% end %>
</div>



      <!-- <button class="btn btn-success btn-block text-left bnt-lg comment" data-toggle="modal" data-target="#instructions">
        <i class="fa fa-edit"></i> Ajouter un commentaire
      </button>
 -->

<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button> -->

<!-- Modal -->

app/views/shops/_product_categories.html.erb
<div class="shop-cat">
  <h4>Catégories de produits</h4>
  <% @product_hash.keys.each_with_index do |product_category, index| %>
    <%= link_to anchor: "cat-#{index}" do %>
      <p><%= product_category %></p>
    <% end %>
  <% end %>
</div>

app/views/shops/_products.html.erb
<div class="shop-products">
  <% @product_hash.each_with_index do |(product_category, products), index| %>
    <div class="products-block">
      <h3 id="<%= "cat-#{index}" %>" style="padding-top: 70px; margin-top: -70px;"><%= product_category %></h3>
      <% products.each do |product| %>
        <div class="product-items">
          <div class="product-content">
            <div class="product-name"><%= product.name %></div>
            <div class="product-description"><%= product.short_description %></div>
          </div>
          <div class="product-price"><%= product.price %> €</div>
          <div class="plus-minus text-right">
            <%= link_to shop_add_path(product.shop, product), remote: true do %>
              <i class="fa fa-plus" aria-hidden="true"></i>
            <% end %>
            <%= link_to shop_reduce_path(product.shop, product), remote: true do %>
              <i class="fa fa-minus" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shops/_shop_banner.html.erb
<div class="page-header-inner">
  <div class="container">
    <div class="shop-cover">
        <div class="cvr" style="background-image:url();">

        </div>
    </div>
    <div class="shop-name">
      <h1 class="mbottom5">
        <%= shop.name %>
      </h1>
      <div>
        <ul class="shop-info">
          <li class="metadata list-unstyled">
            <%= shop.category.try(:name) %>
          </li>
          <li class="metadata list-unstyled">
            <%= shop.address %>
          </li>
          <li class="metadata list-unstyled">
            <%= shop.phone_number %>
          </li>
        </ul>
      </div>
    </div>
    <%#= image_tag 'image-banner-show.jpg', class: 'image-show' %>
    <%= cl_image_tag shop.photo.path, width: 350, height: 200, quality: "auto:eco", crop: :fill, class: 'image-show' unless shop.photo.blank? %>
  </div>
</div>

app/views/shops/_shops_categories.html.erb
<div class="shop-cat">
  <h4>Commerces</h4>
  <% @product_hash.keys.each_with_index do |product_category, index| %>
    <%= link_to products_path(search: params[:search], anchor: "cat-#{index}") do %>
      <p><%= product_category %></p>
    <% end %>
  <% end %>
</div>

app/views/shops/_show_cart.html.erb
<% if @cart %>
  <% @cart.each do |shop_id, orders| %>
  <div class="cart-lines">
    <% if orders && Shop.exists?(id: shop_id) %>
      <h4><%= Shop.find(shop_id).name.capitalize %></h4>
      <% orders.each do |product_id, product| %>
        <%= render 'shops/cart_line', id: product_id, product: product, shop_id: shop_id %>
      <% end %>
    <% end %>
  </div>
  <% end %>
  <div class="cart-line ">
    <h4 class="cart-line-content text-bold">
      Total
    </h4>
    <h4 class="cart-line-price text-bold">
      <%= cart_total @cart %> €
    </h4>
  </div>

<% end %>

app/views/shops/index.html.erb
<% content_for :title_tag do %>
  Search for the best local shops around you
<% end %>


<div class="index-shops">

  <div class="pois">
    <div class="pois-list">
      <div class="container-fluid">
        <div class="row">
        <% @shops.each do |shop|  %>
          <div class="col-xs-6">
            <%= render 'card', shop: shop %>
          </div>
        <% end %>
        </div>
      </div>
      <div class="text-center">
        <%#= link_to_previous_page @shops, 'Page préc.' %>
        <%#= link_to_next_page @shops, 'Page suiv.' %>
        <%= paginate @shops %>
      </div>
    </div>
    <div class="pois-map" id="map"></div>
  </div>

</div>


<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/shops/show.html.erb
<div class="show-body">
  <div class="container">
    <div class="back-to-search">
      <%= link_to :back do %>
        <i class="fa fa-chevron-left" aria-hidden="true"></i> Retour aux résultats
      <% end %>
    </div>
  </div>

  <%= render 'shop_banner', shop: @shop %>


  <div class="shop">
    <div class="container">
      <div class="row no-gutter">
        <div class="col-md-3 hidden-xs hidden-sm">
          <div class="shop-categories shop-nav" data-spy="affix" id="product-categories">

            <%= render 'product_categories' %>
            <div class="shops-nearby">
              <h4>Autres commerces proches</h4>
              <% @shops.each do |shop| %>
                <%# dist = distance shop.try(:distance) %>
                <div class="shop-nearby">
                  <%= cl_image_tag shop.photo.path, width: 40, height: 45, quality: "auto:eco", crop: :fill unless shop.photo.blank? %>
                  <div class="shop-nearby-content">
                    <%= link_to "#{shop.name.capitalize}",
                     shop_path(shop) %>
                    <p class="text-muted"><%= "#{shop.category.name} (#{distance shop.try(:distance)})" %></p>

                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <%= render 'products' %>
        </div>

       <div class="col-md-3">
          <div class="shop-cart shop-nav" data-spy="affix">

            <h3>Votre commande</h3>

            <div id="mycart">
              <%= render 'show_cart' %>
            </div>

            <%= render 'form_order' %>

          </div>
        </div>
      </div>  <!-- row -->
    </div> <!-- container -->
  </div>


<div class="modal fade" id="CommentOrder" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Votre commentaire</h4>
      </div>
      <div class="modal-body">
        <form>
<!--           <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div> -->
          <div class="form-group">
            <label for="message-text" class="control-label"></label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <button type="button" class="btn btn-success" onclick="instruction();">Ajouter</button>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
<script type="text/javascript">
  $(document).ready(function(){

    $('.shop-nav').affix({
      offset: {
        // bottom: ($('#footer').outerHeight(true) + $('.application').outerHeight(true)) + 50,
        // top: ($('.navbar-wagon').outerHeight(true) + $('.application').outerHeight(true)) + 204
        top: $('#product-categories').offset().top - $('.navbar-wagon').outerHeight(true)
      }
    });
    // console.log($('#product-categories').offset().top - $('.navbar-wagon').outerHeight(true));
  });
  function instruction() {
    var MessageText = $('#message-text').val()
    $("#instructions").val(MessageText);
    $("#CommentOrder").modal('hide');
    $("#instruction-text").text(MessageText);
    $("#comment").text('Éditer');
  };
</script>
<% end %>