config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, only: [:index] do
    get :search, :on => :collection
  end

  resources :shops, only: [:index, :show]  do
    get 'add/:id',    to: 'ordered_products#add',     as: 'add'
    get 'remove/:id', to: 'ordered_products#remove',  as: 'remove'
    get 'reduce/:id', to: 'ordered_products#reduce',  as: 'reduce'
  end


  namespace :retailer do
    resources :shops, only: [:index, :show] do
      resources :orders, only: [:show, :update]
    end
  end

  resources :orders, only: [:index, :create, :update, :show]

  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'translations/dictionnary', to: 'translations#dictionnary'
      post 'translations/translate', to: 'translations#translate'
      get 'shops/search', to: 'shops#search'

      resources :translations, only: [ :new ]
    end
  end
  # get '/style', to: 'pages#bootstrap_components'
  get '/clear-session', to: 'orders#clear_session_cart'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="footer-content">
      <ul class="list-inline footer-icons">
        <li><a href="https://deliveroo.fr/fr"><i class="fa fa-youtube"></i></a></li>
        <li><a href="https://www.petitscommerces.fr/"><i class="fa fa-instagram"></i></a></li>
        <li><a href="https://www.lewagon.com/fr/bordeaux"><i class="fa fa-facebook"></i></a></li>
        <li><a href="https://github.com/adrienpoly"><i class="fa fa-twitter"></i></a></li>
      </ul>
      <div class="footer-baseline text-right">
        <p>Click-n.co @LeWagon</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_active_orders.html.erb
<div class="order-">

  <div class="order-list">
    <div class="order-informations header">

    <p class="order-retailer text-center"><strong>N°</strong></p>
    <p class="order-retailer text-center"><strong>Commerce</strong></p>
    <p class="order-retailer text-center"><strong>Date de retrait</strong></p>
    <p class="order-retailer text-center"><strong>Montant</strong></p>
    <p class="order-retailer text-center"><strong>Produits</strong></p>
    </div>
  </div>

  <div class="order-list">
    <% order.each do |order| %>
    <div class="order-informations">
      <p class="order-retailer"><%= order.id %></p>
      <p class="order-retailer">
        <%= order.shop.name.capitalize %>
      </p>
      <p class="order-retailer"><%= order.pick_up_at.strftime('%d %b %Y- %Hh') %></p>
      <p class="order-retailer"><%= order.total_price %>€</p>
      <p class="order-retailer">
        <%= link_to "#order-show", class: "", data: { toggle: "modal", orderid: "#{order.id}" } do %>
          <button class="btn btn-success btn-block">Voir détails</button>
        <% end %>
      </p>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_form_retailer_orders.erb
<div class="order-">

  <div class="order-list">
    <div class="order-informations header">

    <p class="order-retailer text-center">N°</p>
    <p class="order-retailer text-center">Client</p>
    <p class="order-retailer text-center">Date de retrait</p>
    <p class="order-retailer text-center">Prix</p>
    <p class="order-retailer text-center">Statut</p>
    <p class="order-retailer text-center">Action</p>
    </div>
  </div>

  <div class="order-list">
    <% orders.each do |order| %>
    <div class="order-informations">
      <p class="order-retailer"><%= order.id %></p>
      <p class="order-retailer"><% avatar_url = order.user.facebook_picture_url || 'sylvain.png' %>
          <span><%= image_tag avatar_url, class: "avatar" %></span><span> </span><%= order.user.f_name %> <%= order.user.l_name %></p>
      <p class="order-retailer"><%= order.pick_up_at.strftime('%d %b %Y - %Hh') %></p>
      <p class="order-retailer"><%= order.total_price %>€</p>
      <p class="order-retailer"><%= Order.human_enum_name(:status, order.status) %></p>
      <p class="order-retailer"><%= link_to retailer_shop_order_path(@shop, order),
        class: "btn btn-success btn-block see-details" do %>
         Voir détails
      <% end %>
    </div>
    <% end %>

  </div>

  </div>

app/views/shared/_map_box.html.erb
<div class="box-info">
  <div class="photo-icon">
    <%#= cl_image_tag(spa.photo.path, :width => 250, :height => 70, :crop => :fill) %>
  </div>
  <div class="spa-data">
    <h5>
      <%= link_to(shop.name, shop_path(shop)) %>
    </h5>
    <%= shop.address %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <!-- <p class="logo-text"> Click-n.co </p> -->
    <%= cl_image_tag("click-n-co/clicknco.png", height: 50) %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right ">

    <!-- Search form -->
    <form action="/products">
      <div class="products-search">
        <input type="text" id ="products-search-txt" class="navbar-wagon-search-input" name="search" placeholder="Un produit à coté de chez vous">
        <div class="results" id="products-search-results"></div>

        <button type="submit" class="navbar-wagon-search-btn" >
          <i class="fa fa-search"></i>
        </button>
      </div>
    </form>

      <!-- <input type="text" id="products-search-txt" autofocus> -->
      <!-- <div class="results" id="products-search-results"></div> -->


    <!-- <%#= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-shopping-cart"></i>
        <%# if session[:cart] %>
          <div class="badge badge-blue"><%#= session[:cart].size %></div>
        <%# end %>
      </div>
    <%# end %> -->

    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fa fa-shopping-cart fa-2x dropdown-toggle" data-toggle="dropdown"></i>
        <div class="badge badge-green" id="cart-badge"><%= render 'shops/badge' %></div>
          <% unless session[:cart].blank? %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu shop-cart shop-cart-dropdown">

            <%= render 'shops/cart', cart: session[:cart] %>

              <%= link_to 'Poursuivre ma commande', shop_path(session[:cart].keys[0]), class: "btn btn-success btn-block" %>
            </ul>
          <% end %>

        </div>
      </div>
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item hidden-xs hidden-sm">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || 'sylvain.png' %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to orders_path do %>
                <i class="fa fa-shopping-cart"></i>  <%= t(".profile", default: "Mes commandes") %>
              <% end %>
            </li>
            <li>
              <% if current_user.owner? %>
                <%= link_to retailer_shops_path do %>
                  <i class="fa fa-home"></i>  Mes commerces
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%#= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to orders_path do %>
            <i class="fa fa-shopping-cart"></i>  <%= t(".profile", default: "Mes commandes") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
   $(function() {
      new app.Products;
    });

  </script>

<% end %>

app/views/shared/_search_form.html.erb
<div class="container relaxing-moment text-center">

  <div class="row">
    <div class="col-sm-offset-1 col-sm-10">
      <form class="form-searchbar" action=<%= shops_path %>>
        <div class="form-location">
          <Label>Où</Label>
          <input type="text" class="form-control input-lg" id="where" name="where" placeholder="Bordeaux" value="<%= session[:address] %>">
        </div>

        <div class="form-guests hidden-xs hidden-sm">
          <Label>Quoi</Label>

          <select class="form-control input-lg" id="shop_categ" name="category">
            <option></option>
            <option value="" disabled selected style="display: none;">Boucherie, primeur...</option>
            <% @categories.each do |i| %>
              <option value="<%= i.id %>"><%= i.name %></option>
            <% end %>
          </select>
        </div>
        <div class="form-search">
          <button type="submit" class="btn btn-success btn-lg">Miam</button>
        </div>
      </form>
    </div>
  </div>

</div>