config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, only: [:index] do
    get :search, :on => :collection
  end

  resources :shops, only: [:index, :show]  do
    get 'add/:id',    to: 'ordered_products#add',     as: 'add'
    get 'remove/:id', to: 'ordered_products#remove',  as: 'remove'
    get 'reduce/:id', to: 'ordered_products#reduce',  as: 'reduce'
  end


  namespace :retailer do
    resources :shops, only: [:index, :show] do
      resources :orders, only: [:show, :update]
    end
  end

  resources :orders, only: [:index, :create, :update, :show]

  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'translations/dictionnary', to: 'translations#dictionnary'
      post 'translations/translate', to: 'translations#translate'
      get 'shops/search', to: 'shops#search'

      resources :translations, only: [ :new ]
    end
  end
  # get '/style', to: 'pages#bootstrap_components'
  get '/clear-session', to: 'orders#clear_session_cart'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :ordered_products, dependent: :destroy
  belongs_to :user
  belongs_to :shop
  enum status: [:confirmed, :ready, :picked_up, :canceled]
  # enum status: {
  #   :pending => 1,
  #   :processing => 2,
  #   :confirmed => 3,
  #   :ready => 4,
  #   :picked_up => 5,
  #   :canceled => 6
  # }
  # #[:en_attente, :en_cours_de_préparation, :commande_prête, :commande_récupérée, :commande_annulée]
  monetize :total_price_cents

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.attributes.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: [:show]

  def index
    @orders = Order.where(user: current_user)
    @orders_in  = @orders.where("pick_up_at > ?", Date.today ).order(:pick_up_at)
    @orders_out = @orders.where("pick_up_at < ?", Date.today ).order(:pick_up_at)
  end

  def create
    @mycart = []
    session[:cart].each do |shop_id, orders|
      sum = 0
      @order = Order.new()
      @order.user = current_user
      @order.shop_id = shop_id
      @order.pick_up_at = build_date(params[:other][:day], params[:other][:hour])
      @order.instructions = params[:order][:instructions]
      @order.save
      orders.each do |product_id, product|
        ordered_product = OrderedProduct.new(
          order: @order,
          product_id: product_id,
          quantity: product['qty'],
          order_price: product['price'])
        ordered_product.save
        sum += ordered_product.order_price * ordered_product.quantity
      end
      @order.total_price = sum
      @order.confirmed!
      @order.save
      @mycart << @order
    end
    session[:cart] = {}
    #redirect_to new_order_payment_path(@order), notice: 'Order was successfully created.'
    redirect_to new_order_payment_path(@order, my_cart: @mycart)
  end

  def show
    #@order = Order.where(status: :confirmed).find(params[:id])
    render layout: false
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.ready?
      OrderMailer.ready(order).deliver_now
    elsif order.canceled?
      OrderMailer.canceled(order).deliver_now
    end
    redirect_to retailer_shop_path(order.shop)
    #notice: ''
  end

  def clear_session_cart
    session[:cart] = {}
    redirect_to root_path, notice: 'Session was successfully cleared.'
  end

  private

  def find_order
    #@order = Order.find(params[:order_id])
    @order = Order.find(params[:id])
  end

  def build_date(day, hour)
    hour = hour + "h" unless hour.end_with?("h")
    date = DateTime.parse(day + "T" + hour)
  end

  def order_params
    params.require(:order).permit(:status, :instructions)
  end
end

app/controllers/retailer/orders_controller.rb
class Retailer::OrdersController < ApplicationController

  def index
  end

  def show
    @order = Order.find(params[:id])
    @index = Order.statuses[@order.status]
  end

end

app/controllers/retailer/shops_controller.rb
class Retailer::ShopsController < ApplicationController
  def index

    if current_user.shops.one?
      redirect_to retailer_shop_path(current_user.shops.first)
      return
    end
    # Let's anticipate on next week (with login)
    @shops = current_user.shops
    # @shop = current_user.shops.find(params[:id])
  end

  def show
    @shop = Shop.find(params[:id])
    @orders = @shop.orders
    # @orders_in  = @orders.where("pick_up_at > ?", Date.today )
    # @orders_out = @orders.where("pick_up_at < ?", Date.today )
    @orders_confirmed  = @orders.where(status: :confirmed)
    @orders_ready = @orders.where(status: :ready)
    @orders_history = @orders.where(status: :picked_up)

  end

end

app/views/retailer/orders/show.html.erb
<div class="retailer-order-view">
  <div class="order-show">
    <div class="order-first-column">
      <div class="user-infos">
        <% avatar_url = @order.user.facebook_picture_url || 'sylvain.png' %>
        <div class="user-image">
          <%= image_tag avatar_url, class: "avatar-large" %>
        </div>
        <div>
          <p><strong>Client :</strong></p>
          <p><%= @order.user.f_name %> <%= @order.user.l_name %></p>
          <p><%= @order.user.email %></p>
        </div>
      </div>

      <div class="order-details">
        <p><strong>Date</strong> : <%= @order.pick_up_at.strftime('%d %b %Y - %Hh') %></p>
        <p><strong>Instructions</strong> : <%= @order.instructions %></p>
        <p><strong>Montant total</strong> : <%= @order.total_price %>€</p>
      </div>

      <div class="order-status">
        <p><strong>Statut</strong></p>
        <div class="progres">

          <% if !@order.canceled? %>
          <div class="bar-label">

          </div>


            <% 3.times do |i| %>

              <div class="bar-label">
                <% if i  <= @index %>
                  <i class="fa fa-circle done" aria-hidden="true"> </i>
                <% else %>
                  <i class="fa fa-circle-o" aria-hidden="true"></i>
                <% end %>
                <div class="bar-text"><%= Order.human_enum_name(:status, Order.statuses.keys[i]) %></div>
              </div>
              <% if i < 3 && i < @index %>
              <span class="bar done"></span>
              <% elsif i < 2 && i >= @index  %>
              <span class="bar"></span>
              <%  end %>
            <% end %>



          <% else %>

            <div class="label label-warning">Annulée</div>
          <% end %>

        </div>
      </div>


      <div class="product-and-buttons">


        <div class="action-buttons text-center">
        <% if @order.confirmed? %>
          <%#= link_to order_path(@order, order: {status: :pending}), method: :patch,
            class: "btn btn-warning btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
             <!-- Commande en attente -->
          <%# end %>
          <%#= link_to order_path(@order, order: {status: :processing}), method: :patch,
            class: "btn btn-warning btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
             <!-- Commande en cours -->
          <%# end %>
          <%= link_to order_path(@order, order: {status: :ready}), method: :patch,
              class: "btn btn-success btn-block bigger-btn " do %>
               Commande prête
            <% end %>
            <%= link_to order_path(@order, order: {status: :canceled}), method: :patch,
              class: "btn btn-danger btn-block bigger-btn " do %>
               Annuler
            <% end %>
        <%# elsif @order.pending? %>
          <%#= link_to order_path(@order, order: {status: :processing}), method: :patch,
            class: "btn btn-warning btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
             <!-- Commande en cours -->
          <%# end %>
          <%#= link_to order_path(@order, order: {status: :ready}), method: :patch,
            class: "btn btn-success btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
            <!--  Commande prête -->
          <%# end %>
          <%#= link_to order_path(@order, order: {status: :picked_up}), method: :patch,
            class: "btn btn-primary btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
        <!--      Commande récupérée -->
          <%# end %>
          <%# link_to order_path(@order, order: {status: :canceled}), method: :patch,
            class: "btn btn-danger btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
        <!--      Annuler -->
          <%# end %>
        <%# elsif  @order.processing? %>
          <%#= link_to order_path(@order, order: {status: :ready}), method: :patch,
            class: "btn btn-success btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
           <!--   Commande prête -->
          <%# end %>
          <%#= link_to order_path(@order, order: {status: :picked_up}), method: :patch,
            class: "btn btn-primary btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
       <!--       Commande récupérée -->
          <%# end %>
          <%#= link_to order_path(@order, order: {status: :canceled}), method: :patch,
            class: "btn btn-danger btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
             <!-- Annuler -->
          <%# end %>
        <% elsif @order.ready?  %>
          <%= link_to order_path(@order, order: {status: :picked_up}), method: :patch,
             class: "btn btn-primary btn-block bigger-btn " do %>
             Commande récupérée
          <% end %>
          <%= link_to order_path(@order, order: {status: :canceled}), method: :patch,
            class: "btn btn-danger btn-block bigger-btn ", data:{confirm: "Are you sure?"} do %>
             Annuler
          <% end %>

        <% end %>

        </div>
      </div>

    </div>
    <div class="order-second-column">
      <%= render 'orders/order_manifest' %>
    </div>
  </div>

</div>