config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, only: [:index] do
    get :search, :on => :collection
  end

  resources :shops, only: [:index, :show]  do
    get 'add/:id',    to: 'ordered_products#add',     as: 'add'
    get 'remove/:id', to: 'ordered_products#remove',  as: 'remove'
    get 'reduce/:id', to: 'ordered_products#reduce',  as: 'reduce'
  end


  namespace :retailer do
    resources :shops, only: [:index, :show] do
      resources :orders, only: [:show, :update]
    end
  end

  resources :orders, only: [:index, :create, :update, :show]

  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'translations/dictionnary', to: 'translations#dictionnary'
      post 'translations/translate', to: 'translations#translate'
      get 'shops/search', to: 'shops#search'

      resources :translations, only: [ :new ]
    end
  end
  # get '/style', to: 'pages#bootstrap_components'
  get '/clear-session', to: 'orders#clear_session_cart'
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order, only: [:new]

  def new
    @sum = 0
    @table.each do |partial|
      @sum += partial.total_price
    end
    @order = @table.last
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail])

    params[:my_cart].split.each do |id|
      @order = Order.find(id)
      #@order = Order.where(status: :pending).find(params[:order_id])
      charge = Stripe::Charge.create(
      customer:    customer.id,   # You should store this customer id and re-use it.
      amount:      @order.total_price_cents, # or amount_pennies
      description: "Payment for Click-n-co #{@order.shop.name} for order #{@order.id}",
      currency:    @order.total_price.currency)
      @order.update(payment: charge.to_json, status: :confirmed)
      OrderMailer.register(@order).deliver_now
    end
    redirect_to orders_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @table = []
    params[:my_cart].each do |id|
      @table << Order.find(id)
    end
    # @order = Order.where(status: :pending).find(params[:order_id])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class="container payments text-center">
<div class="payments-content">
   <h1 class="text-center payments-title">
     Ma <strong>'Click-n-co'</strong> commande n°<%= @order.id %>
   </h1>

  <div class="order-list">
    <div class="order-informations header">
      <p class="order-retailer text-center">Commerce</p>
      <p class="order-retailer text-center">Adresse</p>
      <p class="order-retailer text-center">Date de retrait</p>
      <p class="order-retailer text-center">Prix</p>
      <p class="order-retailer-products text-center">Produits</p>
    </div>
  </div>



  <%= form_tag order_payments_path(@order) do %>
    <div class="order-list">

      <% @table.each do |order| %>
        <div class="order-informations">
          <p class="order-retailer"><strong><%= order.shop.name.capitalize %></strong></p>
          <p class="order-retailer"><%= order.shop.address %></p>
          <p class="order-retailer"><%= order.pick_up_at.strftime('%d %b %Y- %Hh') %></p>
          <p class="order-retailer"><%= order.total_price %>€</p>
          <div class="order-retailer-products">
            <div class="order-manifest">
              <% order.ordered_products.each do |ordprods| %>
                <div class="order-line">
                  <div class="order-line-content">
                    <span class="order-line-quantity">
                      <%= ordprods.quantity.to_i  %> x
                    </span>
                    <span class="order-product-name">
                      <%= ordprods.product.name %>
                    </span>
                  </div>
                  <div class="order-line-price">
                    <%= ordprods.product.price * ordprods.quantity.to_i  %> €
                  </div>
                </div>
              <% end %>
            </div>

          </div>
        </div>
      <% end %>
    </div>

   <%= hidden_field_tag 'my_cart', params[:my_cart] %>


  <div class="total_price_div">
    <!-- <article> -->
      <label class="total_price">
        <% @order.total_price = @sum %>
        <span>Total : <%= humanized_money_with_symbol(@order.total_price) %></span>
      </label>
    <!-- </article> -->
  </div>

  <div class="pay">
    <!-- Commented for the lecture, remove comments.   -->
     <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      value="Payer"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="Click & Co"
      data-email="<%= current_user.email %>"
      data-description="Click & co"
      data-locale= "auto"
      data-amount="<%= @order.total_price_cents %>"
      data-currency="<%= @order.total_price.currency %>"
      data-image="https://stripe.com/img/documentation/checkout/marketplace.png">
     </script>
   <% end %>
  </div>

</div>